//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBookAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Acquaintance_Transaction = new HashSet<Acquaintance_Transaction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WalletId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acquaintance_Transaction> Acquaintance_Transaction { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual Wallet Wallet { get; set; }
        public virtual Event Event { get; set; }
    }
}
